### ISSUE TITLE
Support Carthage

### ISSUE THREAD

**Issue by schickling** [cezarywojcik/CWStatusBarNotification#63]
Please support [Carthage](https://github.com/Carthage/Carthage) on the Swift 2 branch. You just need to share the build scheme and push it. Thanks!

**Comment by cezarywojcik** [comment]
Should be good to go!

https://github.com/cezarywojcik/CWStatusBarNotification/commit/88623f80a289bb7e416607b289729677eced029c

**Comment by schickling** [comment]
Great!

**Comment by schickling** [comment]
Sorry for the misunderstanding but you need to push the build scheme for the framework, not for the demo.

**Comment by cezarywojcik** [comment]
Ah, I guess the misunderstanding came about because the demo build scheme is the only build scheme. The library was meant to be used by importing the two `*.swift` files.

As an exercise, though, I went ahead and tried settings things up as a framework. I haven't used either Carthage or custom frameworks in the past, though, so I'm hoping I set things up correctly. 

https://github.com/cezarywojcik/CWStatusBarNotification/commit/be8a8e51a901bc54bf133f47b051c46112dd71ff

However, I was only able to get the framework to work myself when using a workspace, though I'm somewhat new to this, so I'm not sure if I'm importing the framework incorrectly or whether something is set up incorrectly.

Let me know if things work as intended for you. If not, feel free to submit a PR.

**Comment by schickling** [comment]
Thanks so much for you effort @cezarywojcik. We're slowly getting there!

Another thing about Carthage. It looks for the schemes in the alphabetically first Xcode project file. So at the moment it takes the demo instead of the framework. Would you mind to change that as well? :+1:

**Comment by cezarywojcik** [comment]
I assumed Carthage would know to choose a framework project. Alphabetical listing seems... silly.

I googled around and it seems like Carthage picks the root-most, alphabetically sorted project. I would prefer not to have to reorganize just because Carthage likes things a certain way. Do you know of a way to just specify the project for Carthage to target? I Googled around real quick and couldn't find a way.

If there's not a way, I'll find a way to reorganize things, but I would prefer not to have to do that.

**Comment by schickling** [comment]
Well at the moment the workaround is the do `carthage checkout`, go the the cloned repository and delete the demo folder by hand before running `carthage build`. I guess that's the price one has to pay by not having a dedicated `Carthage.spec` or something like this.
