### ISSUE TITLE
Possible to offset?

### ISSUE THREAD

**Issue by realsurfer** [cezarywojcik/CWStatusBarNotification#80]
Hi,

To comply with Apple guidelines it would be nice to be able to show the notification bar for example under the navigation bar. Instagram and other apps do this.
Would it be possible to add an offset variable so that it's possible to manually set where the notification appears?

Thanks,
Michael

**Comment by cezarywojcik** [comment]
Apple's guidelines don't seem to be a problem unless you way overuse this kind of functionality.

Since the name of this library is "status bar notification", I'm going to keep it as a status bar notification. There are many edge cases than an offset would not account for - for example, suppose you have an in-call status bar, which is larger than a normal status bar. Something like an offset would complicate this greatly.

Feel free to fork this and add the functionality yourself, but this will remain a status bar notification library.
